version: "3.3"

services:
  # MySQL
  db:
    image: "rohancdev/coe892_project:db"
    container_name: "db"

    build: ./docker/mysql

    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    networks:
      - local-net

  # FastAPI
  patients_api:
    image: "rohancdev/coe892_project:patients_api"
    links:
      - db
    container_name: "patients_api"

    build: ./docker/api
    ports:
      - "8002:8002"
    volumes:
      - ./code:/usr/src/server
    networks:
      - local-net

  symptoms_api:
    image: "rohancdev/coe892_project:symptoms_api"
    links:
      - db
    container_name: "symptoms_api"

    build: ./docker/symptom_api
    ports:
      - "8001:8001"
    volumes:
      - ./code:/usr/src/server
    networks:
      - local-net

  operating_room_api:
    image: "rohancdev/coe892_project:operating_room_api"
    links:
      - db
    container_name: "operating_room_api"

    build: ./docker/operating_room_api
    ports:
      - "8003:8003"
    volumes:
      - ./code:/usr/src/server
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
